version: "3.7"

services:
  bot:
    image: bot:latest
    networks:
      - paintnet

  srv:
    image: srv:latest
    networks:
      - paintnet
    ports:
      - 8000:8000
    env_file:
      - .env

  db:
    image: "postgres:14.1-bullseye"
    networks:
      - paintnet
    ports:
      - 5432:5432
    volumes:
      - /var/lib/postgresql/data
    env_file:
      - .env

networks:
  paintnet: