version: "3.7"

services:
  bot:
    image: bot:latest

  client:
    image: client:latest
    ports:
      - 8080:8080

  srv:
    image: srv:latest
    ports:
      - 8000:8000
    env_file:
      - .env

  db:
    image: "postgres:14.1-bullseye"
    ports:
      - 5432:5432
    volumes:
      - /var/lib/postgresql/data
    env_file:
      - .env
